---
title:
  
  Livro: Estatística Experimental nas Ciências Agrárias
author: 
- Helio de Souza Junior,^[Universidade Estadual de Maringá, helioszjr@gmail.com]
date: 
output:
  html_document:
    toc: true
    toc_float: true
    theme: simplex
    highlight: haddock
    editor_options: 
      chunk_output_type: console
  chunk_output_type: console
---
Repositório dedicado ao ensino na área de Estatística Experimental nas Ciências Agrárias.

Este repositório conta com diversas rotinas do software R voltadas para o auxilio de estudantes. Aqui aborda, experimentos e exercicios em Estatística Experimental aplicada à pesquisa agrícola. Delineamentos experimentais como DIC, DBC e parcelas subdivididas, além de experiência com testes de significância, análise de regressão (incluindo polinômios ortogonais) e análise de covariância.


# Estatística Experimental
Comparativo de Livros sobre Estatística Experimental nas Ciências Agrárias

## 📘 Estatística Experimental Aplicada às Ciências Agrárias

### Capítulos:
- 1. Introdução à estatística experimental  
- 2. Medidas de tendência central e de variabilidade de dados  
- 3. Análise de variância  
- 4. Testes de hipóteses  
- 5. Delineamento inteiramente casualizado  
- 6. Delineamento em blocos casualizados  
- 7. Delineamento em quadrado latino  
- 8. Regressão e correlação  
- 9. Experimentos fatoriais  
- 10. Experimentos em parcelas subdivididas  
- 11. Experimentos em faixas  
- 12. Análise conjunta de experimentos  
- 13. Experimentos em blocos casualizados com alguns tratamentos comuns  
- 14. Análise de covariância  
- 15. Experimentos fatoriais com tratamentos adicionais  
- 16. Experimentos com consorciação de culturas  
- 17. Testes não paramétricos  

---

## 📗 Curso de Estatística Experimental (15ª edição)

### Capítulos:
- 1. Introdução (média, desvio padrão, graus de liberdade etc.)  
- 2. Princípios básicos de experimentação  
- 3. Testes ou provas de significância  
- 4. Experimentos inteiramente casualizados  
- 5. Experimentos em blocos casualizados  
- 6. Experimentos em quadrados latinos  
- 7. Experimentos fatoriais  
- 8. Análise de grupos de experimentos  
- 9. Experimentos em parcelas subdivididas e em faixas  
- 10. Blocos incompletos equilibrados  
- 11. Reticulados (látices quadrados)  
- 12. Uso da regressão na análise de variância  
- 13. Lei de Mitscherlich em adubação com animais  
- 14. Teste de qui-quadrado e aplicações  
- 15. Análise de covariância  
- 16. Análise conjunta de experimentos com tratamentos comuns  
- 17. Experimentos fatoriais com tratamentos adicionais  
- 18. Análise da variância multidimensional  
- 19. Superfícies de resposta  
- 20. Testes não paramétricos  
- 21. Tabelas  

---

## 📙 Experimentação Agrícola (4ª edição)

### Capítulos:
- 1. Introdução  
- 2. Testes de significância  
- 3. Delineamento inteiramente casualizado  
- 4. Delineamento em blocos casualizados  
- 5. Experimentos fatoriais  
- 6. Experimentos em parcelas subdivididas  
- 7. Análise de regressão por polinômios ortogonais  
- 8. Análise de grupos de experimentos  
- 9. Análise de covariância  
- 10. Literatura citada  
- 11. Tabelas

## Referências

- **Referências Bibliográficas:** BANZATTO, David A.; KRONKA, Sérgio do N. Experimentação agrícola. 4. ed. Jaboticabal: FUNEP, 2006.

- **Referências Bibliográficas:** PIMENTEL-GOMES, Frederico. Curso de estatística experimental. 15. ed. Piracicaba: FEALQ, 2009. (Volume 15).

- **Referências Bibliográficas:** ZIMMERMANN, Francisco José Péliasticker. Estatística aplicada à pesquisa agrícola. 2. ed. rev. e ampl. Brasília, DF: Embrapa Informação Tecnológica, 2004.
